spring:
  application:
    # 服务名
    name: online-learning-student-web
  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: 47.104.253.73:8848
    sentinel:
      transport:
        dashboard: 47.104.253.73:8888
server:
  # 服务端口
  port: 8010
management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"