spring:
  application:
    # 服务名
    name: online-learning-student-web
  cloud:
    sentinel:
      transport:
        dashboard: 47.104.253.73:8888
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: -1ms
        min-idle: 0
    host: 39.105.154.17
    port: 6379
    password: 950405
    timeout: 50000
  datasource:
    username: musuixin
    password: CSRQ19971031yu
    url: jdbc:mysql://rm-bp1783uv4c566u27tmo.mysql.rds.aliyuncs.com/online_learning?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idleTimeout: 10000
      minimumIdle: 5
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 20MB
server:
  # 服务端口
  port: 8010
management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    top.musuixin: trace
    com.alibaba.nacos.client: error
  file: /logs/online-learning-student-web.log
knife4j:
  production: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
  ## Basic认证用户名
    username: root
  ## Basic认证密码
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:db/*.xml
