server:
  port: 8000
spring:
  application:
    name: online-learning-monitor
  mail:
    host: smtp.qq.com
    username: 1804125652@qq.com
    password: qfkxfnnnvwmjeaag
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          to: 1154430034@qq.com
          from: 1804125652@qq.com

#  #邮箱服务
#  spring.mail.host=smtp.qq.com
#  #邮箱地址
#  spring.mail.username=251630606@qq.com
#  #qq邮箱授权码，如果是其他邮箱一般为密码，具体看邮箱要求
#  spring.mail.password=----------------
#  # 设置是否需要认证，如果为true,那么用户名和密码就必须的，
#  #如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的。
#  spring.mail.properties.mail.smtp.auth=true
#  #STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信
#  #服务器需要tls验证
#  spring.mail.properties.mail.smtp.starttls.enable=true
#  spring.mail.properties.mail.smtp.starttls.required=true
#  # 发送给谁
#  spring.boot.admin.notify.mail.to=sunhuansheng@dhcc.com.cn
#  # 是谁发送出去的
#  spring.boot.admin.notify.mail.from=251630606@qq.com