server:
  port: 8081
#  servlet:
#    context-path: "/student"
spring:
  boot:
    admin:
      client:
        url: "http://127.0.0.1:8000/"
management:
  endpoints:
    web:
      exposure:
        include: "*"
