spring:
  datasource:
    username: *
    #设置mysql的用户名
    password: *
    #设置mysql的密码
    url: *
    #设置mysql的地址
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idleTimeout: 10000
      minimumIdle: 5
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  application:
    # 服务名
    name: online-learning-LoginRegister-web
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    host: *
    #在此设置自己的redis服务地址
    port: *
    #设置自己的redis端口
    password: *
    #设置自己的redis密码，如果没有则无需设置
    timeout: 10000
  servlet:
    multipart:
      max-file-size: 20MB
server:
  # 服务端口
  port: 8000
management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    top.musuixin: trace
  file: ./online-learning-LoginRegister-web.log
knife4j:
  production: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    ## Basic认证用户名
    username: root
    ## Basic认证密码
    password: 123456