spring:
  datasource:
    username: musuixin
    password: CSRQ19971031yu
    url: jdbc:mysql://rm-bp1783uv4c566u27tmo.mysql.rds.aliyuncs.com/online_learning?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      default-transaction-isolation: 2
  application:
    # 服务名
    name: online-learning-LoginRegister-web
  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: 47.104.253.73:8848
    sentinel:
      transport:
        dashboard: 47.104.253.73:8888
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    host: 39.105.154.17
    port: 6379
    password: 950405
    timeout: 10000
server:
  # 服务端口
  port: 8000
management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    top.musuixin: trace
  file: F:\logger\online-learning-LoginRegister-web.logs
